# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
$:.unshift File.expand_path('../../lib', __FILE__)
require 'naka'
require 'webmock/rspec'

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'

  config.before { Naka::User.stub(:namespace) { "ijn48:naka:user:test" } }

  def mock_file(path)
    File.read File.expand_path("../support/#{path}", __FILE__)
  end

  def user
    Naka::User.new(id: 1, api_host: '0.0.0.0', api_token: 'token', api_at: 0)
  end
end
